flowchart TD

A[Telegram Mini App]

A --> B[Client Area]
A --> C[Store]
A --> D[Account]
A --> E[Help]
A --> F[Learn]

F --> G[Privacy Lab]

G --> H[Simulations]
G --> I[Solution Finder]

I --> J[Narayana Products]
